'use client';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from './components/Header';
import { Footer } from './components/Footer';
import clsx from 'clsx';
import { useState } from 'react';
import { MobMenu } from './components/MobMenu';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='px-10 max-md:px-0 md:pt-8'>
          <Header onOpen={() => setIsMenuOpen(true)} />
          {isMenuOpen && (
            <div className='bg-white z-1000 absolute top-0 left-0 shadow-2xs w-[340px]'>
              <MobMenu onClose={() => setIsMenuOpen(false)} />
            </div>
          )}
        </div>
        {children}

        <Footer />
      </body>
    </html>
  );
}
